ALTER TABLE models
  ADD COLUMN IF NOT EXISTS input_cache_read_price_per_1m NUMERIC(14,6) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS input_cache_write_price_per_1m NUMERIC(14,6) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS request_price_flat NUMERIC(14,6) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS supports_structured_outputs BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS supports_reasoning BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS input_modalities TEXT[] DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS output_modalities TEXT[] DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS is_moderated BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS max_completion_tokens INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS expiration_date DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS openrouter_model_id TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS metadata_synced_at TIMESTAMPTZ DEFAULT NULL;
